[package]
name = "project_aira"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
rodio = "0.19.0"
cpal = "0.16.0"
crossterm = "0.27"

aira_brain = { path = "aira_brain" }

[workspace]
members = [
  "aira_brain",
  "aira_server"
]
