[package]
name = "aira_brain"
version = "0.1.0"
edition = "2024"

[dependencies]

whisper-rs = { version = "0.15.1", features = ["cuda"] }
llama_cpp = "0.3.2"
anyhow = "1.0.100"
piper-rs = "0.1.9"
tract-onnx = "0.21.0"
hound = "3.5.1"
